#!/bin/bash

script_path=$(readlink -f ${BASH_SOURCE[0]})
wfdir=$(dirname "${script_path}")
image="${wfdir}/00scripts/rnaseq.img"

SINGULARITY_BINDPATH="/gpfs,/gs2,/gs3,/gs4,/gs5,/gs6,/spin1,/data,/scratch,/fdb,/lscratch"
export SINGULARITY_BINDPATH

singularity exec ${image} bash "$@"
